import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Portfolio from "@/components/Portfolio";
import Services from "@/components/Services";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const toggleMode = () => {
    setDarkMode(!darkMode);
    console.log("mode changed");
  };
  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Freelancing Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="dark:bg-gray-900">
          <Navbar toggleMode={toggleMode} />
          <Hero />
          <Services />
          <Portfolio />
        </div>
      </div>
    </>
  );
}
